---
- name: Allow ipmi_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ ipmi_exporter_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: configure ipmi exporter
  template:
    src: ipmi_exporter.yml.j2
    dest: "{{ ipmi_exporter_config_file }}"
    owner: "{{ ipmi_exporter_system_user }}"
    group: "{{ ipmi_exporter_system_group }}"
    mode: '0600'
  notify:
    - restart ipmi_exporter