---
- name: Allow ipmi_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ ipmi_exporter_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: Deploy configuration file
  copy:
    content: |
      #
    dest: "{{ ipmi_exporter_config_file }}"
    owner: "{{ ipmi_exporter_system_user }}"
    group: "{{ ipmi_exporter_system_group }}"
    mode: '0600'
  when: ipmi_exporter_config_file is defined
