---
- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in ipmi_exporter_web_listen_address"

- name: Fail on unsupported init systems
  fail:
    msg: "This module only works with systemd"
  when: ansible_service_mgr != 'systemd'

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/soundcloud/ipmi_exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: true
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set ipmi_exporter version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        ipmi_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"
  when: ipmi_exporter_version == "latest"

#- name: "Get checksum for {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }} architecture"
#  set_fact:
#    ipmi_exporter_checksum: "{{ item.split(' ')[0] }}"
#  with_items:
#    - "{{ lookup('url', 'https://github.com/soundcloud/ipmi_exporter/releases/download/v' + ipmi_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
#  when: "('linux-' + (go_arch_map[ansible_architecture] | default(ansible_architecture)) + '.tar.gz') in item"

- name: Get systemd version
  shell: systemctl --version | awk '$1 == "systemd" {print $2}'
  changed_when: false
  check_mode: false
  register: ipmi_exporter_systemd_version
  tags:
    - skip_ansible_lint
